version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-chatgpt-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEATHERAPI_KEY=${WEATHERAPI_KEY}
      - ALLOWED_USER_IDS=${ALLOWED_USER_IDS}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"